export const SOME_ACTION_TYPE = 'SOME_ACTION_TYPE';
export const LOGIN_ACTION_TYPE = 'LOGIN_ACTION_TYPE';
export const LOGOUT_ACTION_TYPE = 'LOGOUT_ACTION_TYPE';
export const SET_ERROR_ACTION_TYPE = 'SET_ERROR_ACTION_TYPE';
export const SET_APP_TITLE_ACTION_TYPE = 'SET_APP_TITLE_ACTION_TYPE';

