export const SOME_ACTION_TYPE = 'SOME_ACTION_TYPE';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const APP_SET_ERROR = 'APP_SET_ERROR';
export const APP_SET_TITLE = 'APP_SET_TITLE';

export const COURSES_CREATE = 'COURSES_CREATE';
export const COURSES_READ = 'COURSES_READ';
export const COURSES_UPDATE = 'COURSES_UPDATE';
export const COURSES_REMOVE = 'COURSES_REMOVE';

