export const SOME_ACTION_TYPE = 'SOME_ACTION_TYPE';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const APP_SET_ERROR = 'APP_SET_ERROR';
export const APP_SET_TITLE = 'APP_SET_TITLE';


export const COURSES_GET_START = 'COURSES_GET_START';
export const COURSES_GET_END = 'COURSES_GET_END';

export const COURSES_READ_START = 'COURSES_READ_START';
export const COURSES_READ_END = 'COURSES_READ_END';

export const COURSES_CREATE = 'COURSES_CREATE';
export const COURSES_UPDATE = 'COURSES_UPDATE';
export const COURSES_REMOVE = 'COURSES_REMOVE';

